#!/bin/bash

echo "Running detekt check..."
./gradlew detekt
EXIT_CODE=$?
if [ $EXIT_CODE -ne 0 ]; then
  echo "***********************************************"
  echo "                 detekt failed                 "
  echo " Please fix the above issues before committing "
  echo "***********************************************"
  exit $EXIT_CODE
fi

echo "Verifying With ktlint"

./gradlew lintKotlin
status=$?
if [ "$status" = 0 ] ; then
    echo "No problems"
    exit 0
else
    echo "Formatting..."
    ./gradlew formatKotlin
    result=$?
    if [ "$result" = 0 ] ; then
        echo "Done format, check changes"
        exit 1
    else
        echo 1>&2 "Error, need manual!"
        exit 1
    fi
fi